let data = [{
    "Articulo": 1,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": 42,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Una expresiva mediasuela fluida y tecnología moderna proporcionan un estilo audaz y comodidad de primer nivel a las nuevas Run Star Motion.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw85861e5d/images/a_107/172066C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 2,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 50,
    "Talla Zapatos": 45,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "Los estampados de teñido anudado y los detalles envejecidos hechos a mano aportan un aspecto atrevido y desgastado a las Chuck clásicas.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw82a20780/images/a_107/A02119C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 3,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 5,
    "Talla Zapatos": 39,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "Las mejores Chuck 70 de la historia se adentran en la naturaleza con un diseño concienciado con el medioambiente y un estilo inspirado en el senderismo.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw4adce1bd/images/a_107/A00486C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 4,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 25,
    "Talla Zapatos": 44,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "La lona lavada da un estilo desgastado a tus sneakers favoritas (¡aunque estén recién salidas de la caja!).",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw8fbd1898/images/a_107/A02584C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 5,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 5,
    "Talla Zapatos": 39,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "The iconic fabrics of Carhartt WIP inspire a premium Chuck 70 high top.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw52fbd31f/images/a_107/169221C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 6,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": 40,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "l mejor modelo de la historia recibe una actualización para la temporada con lona premium en un color clásico.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw97d70121/images/a_107/162058C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 7,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 25,
    "Talla Zapatos": 43,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Personajes inolvidables en un estilo atemporal: Snoopy y Emilio en unas One Star de ante.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwd2eaff17/images/a_107/A01873C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 8,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": 44,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Los elementos de diseño icónicos de las Chuck Taylor se rediseñan y se reinventan para crear una nueva versión de las mejores Chuck 70 hasta la fecha.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw0ffb4943/images/a_107/A02115C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 9,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": 39,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Crea tus propias Chuck",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://secure-render.nike.com/ir/render/nikeidrender/DGSPeanutsSU22_v3?obj=/s/g2&color=34394b&show&obj=/s/g4&color=eae5d9&show&obj=/s/g5&color=b50024&show&obj=/s/g9&color=eae5d9&show&obj=/s/g10&color=eae5d9&show&obj=/s/g11&color=D2232A&show&obj=/s/g12&color=27364a&show&obj=/s/g20&color=634437&show&obj=/s/g13&color=151416&show&obj=/s/g17/linus&show&obj=/s/g19/woodstock&show&obj=/s/g22/franklin&show&obj=/s/g14&color=eae5d9&show&obj=/s&req=object&fmt=png-alpha&icc=AdobeRGB&wid=1600"
  },
  {
    "Articulo": 10,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": 42,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Una leyenda del baloncesto se actualiza con detalles envejecidos. Tu imprescindible para el día a día.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwb4352882/images/a_107/169120C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 11,
    "Niño/Adulto": "Niño",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "Los estampados de códigos de barras aportan un estilo digital atrevido a las sneakers favoritas de tu peque.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw5a940bf5/images/a_107/372859C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 12,
    "Niño/Adulto": "Niño",
    "Sexo": "M",
    "Rebajas %": 5,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Estas sneakers ideales para la cancha se han reinventado para niños y niñas mediante tiras para ponérselas y quitárselas fácilmente y detalles suavizados.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw2c612161/images/a_107/372883C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 13,
    "Niño/Adulto": "Niño",
    "Sexo": "M",
    "Rebajas %": 25,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plataforma",
    "Descripción": "Los revestimientos de piel con bloques de color y la amortiguación con sujeción ayudan a mantener la comodidad de los más pequeños conservando el estilo.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw8061d718/images/a_107/372837C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 14,
    "Niño/Adulto": "Niño",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "0-12 meses",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Estas zapatillas suelen venir grandes. Te recomendamos pedir media talla menos.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwcefd6816/images/a_107/7J237_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 15,
    "Niño/Adulto": "Niño",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "0-12 meses",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Estas zapatillas suelen venir grandes. Te recomendamos pedir media talla menos.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwc1f6a75b/images/a_107/709447F_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 16,
    "Niño/Adulto": "Niño",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "0-12 meses",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Los bebés tendrán un look adorable con estas Chuck de corte alto.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwdecee9c7/images/a_107/7J253_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 17,
    "Niño/Adulto": "Niño",
    "Sexo": "M",
    "Rebajas %": 50,
    "Talla Zapatos": "0-12 meses",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Los estampados inspirados en la naturaleza les dan a las Chuck de tu pequeño/a el estilo perfecto para ir de acampada.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw37126a12/images/a_107/772441C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 18,
    "Niño/Adulto": "Niño",
    "Sexo": "Unisex",
    "Rebajas %": 5,
    "Talla Zapatos": "1-4 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Estilo deportivo en tallas para peques y con correas seguras y fáciles de atar.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwedc9e3b9/images/a_107/A01612C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 19,
    "Niño/Adulto": "Niño",
    "Sexo": "F",
    "Rebajas %": 25,
    "Talla Zapatos": "1-4 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Los motivos florales coloridos les dan un aspecto divertido y artesanal a estas Chuck fáciles de poner.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw229e6139/images/a_107/772754C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 20,
    "Niño/Adulto": "Niño",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "1-4 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "El icónico estilo Chuck Taylor está preparado para el frío con piel duradera, forros de felpa suave y correas fáciles de atar para mantener la comodidad.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw7eecac7c/images/a_107/771525C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 21,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": 37,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Las Chuck con plataforma se preparan para el verano con una confección de lona ligera y motivos florales bordados en colores vivos.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw0ca5564e/images/a_107/A02198C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 22,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 5,
    "Talla Zapatos": 39,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "Las flores bordadas y los toques de color originales expresan tu estilo en estas Chuck con plataforma.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw41f4c820/images/a_107/A01592C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 23,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 25,
    "Talla Zapatos": 41,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Lleva tu estilo veraniego al siguiente nivel con este atrevido modelo de jacquard con plataforma y diseños tonales bordados.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw85c25004/images/a_107/A02233C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 24,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 25,
    "Talla Zapatos": 36,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Los toques de oro brillante y los estampados místicos de aluminio elevan los platos de la plataforma.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwb0d80a83/images/a_107/A02205C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 25,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 50,
    "Talla Zapatos": 40,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Los estampados florales y las suelas exteriores de colores realzan cualquier conjunto.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw569465d5/images/a_107/A01593C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 26,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 25,
    "Talla Zapatos": 41,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Una colaboración entre Converse y Beyond Retro le da un toque vintage a las Jack Purcell que mezcla una estética entre artesanal y universitaria para crear un nuevo estilo para este icono.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw47ee8213/images/a_107/A00456C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 27,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": 38,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Vuelve el icono. Esta vez, en lona y poliéster reciclados en nuevos colores: hiperrosa y citrón claro, inspirados en colores superbrillantes que se encuentran en la realidad digital.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw50511850/images/a_107/170157C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 28,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": 36,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "El mejor modelo de la historia recibe una actualización para la temporada con lona premium en un color clásico.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwb6140341/images/a_107/162062C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 29,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "L",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Camiseta de corte clásico, logo icónico.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwa8fa25f8/images/a_107/10024241-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 30,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 5,
    "Talla Zapatos": "-",
    "Talla Ropa": "S",
    "Ropa arriba/abajo": "abajo",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Un pantalón corto de algodón suave diseñado para hacer ejercicio y ofrecer un estilo informal para el día a día.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwff4a90ca/images/a_107/10024197-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 31,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 25,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "abajo",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Tu pantalón corto básico para las vacaciones con el estilo de Converse.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw657abc82/images/a_107/10023278-A03_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 32,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 5,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Tu camiseta básica para las vacaciones con el estilo de Converse.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwed205351/images/a_107/10023277-A03_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 33,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "L",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "La clásica camisa con botones se reinventa para el trabajo en un taller.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw2ad8bd7e/images/a_107/10022950-A04_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 34,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 5,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "La sudadera con capucha Converse Shapes Bubble Graphic está diseñado meticulosamente para desafiar el tallaje y las etiquetas de género tradicionales.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw054024f9/images/a_107/10022372-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 35,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 25,
    "Talla Zapatos": "-",
    "Talla Ropa": "S",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "La sudadera con capucha de corte clásico se perfecciona aún más con diseños florales nostálgicos que reparten mucho amor.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw05e1bde1/images/a_107/10023949-A03_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 36,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "L",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Prenda de algodón suave con un ajuste clásico que ofrece comodidad en el día a día.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw1bc9c3f1/images/a_107/10023637-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 37,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "abajo",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "El estilo urbano se combina con la funcionalidad en este diseño para el día a día.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw9a275ae0/images/a_107/10021936-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 38,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": 39,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "El diseño Color Block en tonos pastel añade un toque suave a las codiciadas Run Star Hike.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw6b488ada/images/a_107/A01582C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 39,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": 37,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Las mejores Chuck 70 se actualizan con lona premium y una suela exterior de tracción dentada para crear un modelo inspirado en el senderismo.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw12467033/images/a_107/A02093C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 40,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 5,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "A limited-edition backpack celebrates the iconic Peanuts comic strip.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw1a4d68ed/images/a_107/10024379-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 41,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "A limited-edition reversible bucket hat celebrates the iconic Peanuts comic strip.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw03aaa9c2/images/a_107/10024378-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 42,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Átate las zapatillas a tu gusto con los cordones Converse Flat High Top de 91 cm.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwe177abc5/images/a_107/10000978-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 43,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Estos cómodos calcetines cuentan con amortiguación estratégica y son ideales para combinar con tus Chuck favoritas.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw56e231de/images/a_107/10023046-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 44,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 5,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Your go-to top loader bag, scaled down in size.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwef6945e9/images/a_107/10022090-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 45,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 25,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "The cinch-top bucket bag gets scaled down in size – now reimagined in smooth satin.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw500f55d5/images/a_107/10022091-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 46,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Este accesorio básico con el logotipo clásico de estrella y galón te ayuda a marcar estilo.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw4bca14c0/images/a_107/10008479-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 47,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 50,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "A limited-edition classic drawstring backpack highlights the collaboration with DRKSHDW.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw1915e9f7/images/a_107/10022841-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 48,
    "Niño/Adulto": "Niño",
    "Sexo": "M",
    "Rebajas %": 25,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Celebra los 25 años de Pokémon con una mochila electrificada de Pikachu para guardar tus básicos.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwec72531b/images/a_107/10023904-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 49,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Disfruta de la máxima ligereza y sencillez con este bolso musette.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw7e71be67/images/a_107/10023240-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 50,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 25,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "El tejido Sherpa cálido y acolchado, y un bolsillo oculto con cremallera aportan un toque inesperado de calidez y estilo a la temporada de las bufandas.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw2e47d63b/images/a_107/10022379-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 51,
    "Niño/Adulto": "Niño",
    "Sexo": "F",
    "Rebajas %": 5,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "abajo",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "El estampado de camuflaje con estrellas y el logotipo de color neón añaden un estilo urbano increíble al look de los peques.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw207faf8b/images/a_107/10021785-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 52,
    "Niño/Adulto": "Niño",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Átate las zapatillas a tu gusto con los cordones Converse Flat High Top de 91 cm.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwe177abc5/images/a_107/10000978-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 53,
    "Niño/Adulto": "Niño",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "El diseño corto y los estampados por toda la prenda ayudan a los más pequeños a mantener la comodidad y el estilo.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw2f885715/images/a_107/10023535-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 54,
    "Niño/Adulto": "Niño",
    "Sexo": "M",
    "Rebajas %": 50,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Los auténticos logotipos Converse aportan un toque atrevido a la camiseta para el día a día de los más pequeños.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw90042c7e/images/a_107/10023563-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 55,
    "Niño/Adulto": "Niño",
    "Sexo": "Unisex",
    "Rebajas %": 50,
    "Talla Zapatos": "1-4 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Unas Chuck fáciles de poner para peques con criaturas marinas reales y míticas.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwc6acbc8b/images/a_107/A01621C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 56,
    "Niño/Adulto": "Niño",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "0-12 meses",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Los bebés tendrán un look adorable con estas Chuck de corte alto.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwdecee9c7/images/a_107/7J253_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 57,
    "Niño/Adulto": "Niño",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Los motivos florales coloridos dan un aspecto divertido y artesanal a las Chuck favoritas de los niños y niñas.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwfacd1010/images/a_107/372756C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 58,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Esta mochila de inspiración náutica lleva todas tus cosas vayas donde vayas.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwdd0a8b18/images/a_107/10023239-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 59,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Mantén la frescura con este gorro Boonie confeccionado con un 100 % de lona reciclada.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwff8b81a5/images/a_107/10023008-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 60,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": 39,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Una expresiva mediasuela fluida y tecnología moderna proporcionan un estilo audaz y comodidad de primer nivel a las nuevas Run Star Motion.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwcdd3888b/images/a_107/172247C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 61,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 5,
    "Talla Zapatos": 36,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Las codiciadas Run Star Hike se actualizan para el verano con lona forrada de malla transpirable y motivos bordados en colores vivos.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwfdfeef9b/images/a_107/A02192C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 62,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 25,
    "Talla Zapatos": 41,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "Los sutiles estampados dorados, inspirados en el misticismo y la naturaleza, expresan tu estilo en las mejores Chuck 70 de la historia.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwe77bf86a/images/a_107/A02207C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 63,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": 38,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Una suela de plataforma más alta y detalles brillantes con degradado elevan tu estilo veraniego.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw1d1e58c2/images/a_107/A00558C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 64,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 25,
    "Talla Zapatos": 40,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "Las popularísimas Run Star Hike reciben una actualización audaz con lunares grandes y pequeños en contraste.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw149fdebc/images/a_107/A01181C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 65,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "L",
    "Ropa arriba/abajo": "abajo",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Los detalles en la costura delantera aportan sofisticación al codiciadísimo pantalón de chándal de french terry.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw2b270e93/images/a_107/10022965-A05_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 66,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 50,
    "Talla Zapatos": "-",
    "Talla Ropa": "L",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Combina con estilo esta prenda oversize abotonada con retales y diseño Color Block.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwc5057a9c/images/a_107/10022971-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 67,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "S",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "La gabardina 3-In-1 lleva la versatilidad hasta al más mínimo detalle.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw276322c3/images/a_107/10022962-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 68,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Las manchas de leopardo en los colores del arcoíris y la capucha con bloques de color destacan sobre la felpa supersuave.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwb25f7245/images/a_107/10023080-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 69,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "El ajuste relajado del punto de algodón suave y el atrevido estampado de leopardo lleno de color revitalizan tu camiseta de manga larga para el día a día.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw83e6c740/images/a_107/10023057-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 70,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 25,
    "Talla Zapatos": "-",
    "Talla Ropa": "S",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Esta chaqueta versátil combina dos estilos para el frío en una misma prenda.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwe19aa88d/images/a_107/10022733-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 71,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "La camiseta de corte clásico transmite un mensaje de positividad, gratitud y amabilidad.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw04681b09/images/a_107/10024226-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 72,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 5,
    "Talla Zapatos": "-",
    "Talla Ropa": "S",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Esparce las semillas de la positividad, la gratitud y la amabilidad con tu camiseta de corte clásico.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw94e7555a/images/a_107/10024227-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 73,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Todo lo que necesitas en una sudadera con capucha y nada que se interponga en tu camino.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw50c18cb2/images/a_107/10019923-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 74,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "S",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Tu camiseta para todos los días se ha mejorado con un tejido de punto de algodón suave y estampados auténticos All Star.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw810e9dde/images/a_107/10023315-A02_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 75,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 5,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Tu camiseta para todos los días se ha mejorado con un tejido de punto de algodón suave y estampados auténticos All Star.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw9b5c081a/images/a_107/10023320-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 76,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "L",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "A limited-edition t-shirt celebrates the iconic Peanuts comic strip.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw59eb5ea9/images/a_107/10024374-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 77,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 50,
    "Talla Zapatos": "-",
    "Talla Ropa": "S",
    "Ropa arriba/abajo": "abajo",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Esta prenda unisex de edición limitada rinde homenaje a los inolvidables personjes de Snoopy.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw862013f5/images/a_107/10024382-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 78,
    "Niño/Adulto": "Niño",
    "Sexo": "Unisex",
    "Rebajas %": 50,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "A limited-edition t-shirt celebrates the iconic Peanuts comic strip.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwdb782268/images/a_107/10024375-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 79,
    "Niño/Adulto": "Niño",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "abajo",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Limited-edition shorts celebrate the iconic Peanuts comic strip.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwfca035ad/images/a_107/10024377-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 80,
    "Niño/Adulto": "Niño",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "A limited-edition gender-free polo celebrates the iconic Peanuts comic strip.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwddc36da0/images/a_107/10024381-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 81,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 50,
    "Talla Zapatos": "-",
    "Talla Ropa": "S",
    "Ropa arriba/abajo": "abajo",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "El dobladillo con cordón, la cintura elástica y el cierre con hebilla regulable añaden más comodidad a tu pantalón favorito donde quiera que vayas.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwed5969b9/images/a_107/10022945-A03_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 82,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 25,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "La prenda más versátil de nuestra colección de prendas de abrigo modulares, diseñada ofrecerte un look por capas a la última.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw3f299239/images/a_107/10022614-A03_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 83,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "abajo",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Este pantalón de ajuste entallado está diseñado para ofrecer un rendimiento perfecto para la cancha. Ahora incorpora un estampado de leopardo por toda la superficie para ofrecer un estilo que destaca dentro y fuera de la cancha.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwfea30bf3/images/a_107/10022292-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 84,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 5,
    "Talla Zapatos": "-",
    "Talla Ropa": "L",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Hemos trabajado duro para transformar nuestro proceso de producción mediante la creación de Converse Renew, nuestra lona respetuosa con el medio ambiente.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwad986798/images/a_107/10021574-A03_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 85,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "S",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Tu camiseta favorita ahora tiene un gráfico de zapatería tradicional con el estilo de Converse.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw464be870/images/a_107/10023258-A03_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 86,
    "Niño/Adulto": "Niño",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "1-4 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Unas Chuck deportivas con amortiguación para los peques con mucho estilo.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwc5cdd4e7/images/a_107/A02594C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 87,
    "Niño/Adulto": "Niño",
    "Sexo": "Unisex",
    "Rebajas %": 25,
    "Talla Zapatos": "1-4 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "Un estampado de helados divertido hace que estas zapatillas de corte alto sean aún más dulces.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw09ed8dc9/images/a_107/A00395C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 88,
    "Niño/Adulto": "Niño",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plataforma",
    "Descripción": "Los motivos florales coloridos les dan un aspecto divertido y artesanal a las plataformas favoritas de las niñas.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwf4a72eaa/images/a_107/272848C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 89,
    "Niño/Adulto": "Niño",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "La plataforma ultraligera, que favorece la libertad de movimiento, se reduce para los más pequeños.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwe3f6928d/images/a_107/371527C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 90,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 5,
    "Talla Zapatos": 39,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "Las sutiles rayas con textura y los revestimientos de colores sacan a relucir el estilo característico de las Chuck 70 premium.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw7b5862ad/images/a_107/572865C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 91,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": 37,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "Regálate flores que no se marchitarán con las Chuck de plataforma inspiradas en los pétalos.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwd7495a13/images/a_107/A02105C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 92,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": 40,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plataforma",
    "Descripción": "A smokey vintage wash and distressed rubber details bring a well-loved look to the premium Chuck 70.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw5c2c734d/images/a_107/169932C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 93,
    "Niño/Adulto": "Adulto",
    "Sexo": "M",
    "Rebajas %": 25,
    "Talla Zapatos": 44,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "En los años 70, las sneakers Pro Leather se hicieron un lugar como uno de los modelos de baloncesto más icónicos de la historia.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwed9e83ec/images/a_107/169024C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 94,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Duplica el color con este gorro reversible tipo pescador.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwaeeed53e/images/a_107/10023011-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 95,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 50,
    "Talla Zapatos": 41,
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "Las mejores Chuck 70 hasta la fecha se actualizan con un aplique en forma de corazón para que muestres tu amor con tus sneakers.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwe657da10/images/a_107/A02103C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 96,
    "Niño/Adulto": "Adulto",
    "Sexo": "F",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "M",
    "Ropa arriba/abajo": "arriba",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "El moderno estilo color-block se combina con un estampado de leopardo sacado de nuestros archivos para ofrecer un estilo audaz.",
    "Categoria": "Ropa",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwccc71860/images/a_107/10023053-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 97,
    "Niño/Adulto": "Adulto",
    "Sexo": "Unisex",
    "Rebajas %": 0,
    "Talla Zapatos": "-",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "-",
    "Tipo de suela": "-",
    "Descripción": "Celebrate Pride with a vibrant patchwork print that represents Found Family.",
    "Categoria": "Accessorios",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw43ae05c2/images/a_107/10024274-A01_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 98,
    "Niño/Adulto": "Niño",
    "Sexo": "Unisex",
    "Rebajas %": 25,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plataforma",
    "Descripción": "El degradado con brillo aporta más glamour a estas zapatillas de corte bajo con plataforma.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw337fcf3d/images/a_107/A00445C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 99,
    "Niño/Adulto": "Niño",
    "Sexo": "Unisex",
    "Rebajas %": 5,
    "Talla Zapatos": "1-4 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Bajo",
    "Tipo de suela": "Plana",
    "Descripción": "Deja que tu peque celebre el verano con los estampados alegres de frutas de sus sneakers fáciles de poner favoritas.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dwb48fee25/images/a_107/A02605C_A_107X1.jpg?sw=2000"
  },
  {
    "Articulo": 100,
    "Niño/Adulto": "Niño",
    "Sexo": "M",
    "Rebajas %": 0,
    "Talla Zapatos": "4-12 años",
    "Talla Ropa": "-",
    "Ropa arriba/abajo": "-",
    "Tipo de corte": "Alto",
    "Tipo de suela": "Plana",
    "Descripción": "Motivos florales coloridos les dan un aspecto divertido y artesanal.",
    "Categoria": "Zapatos",
    "Dirección de imagen": "https://www.converse.com/dw/image/v2/AALW_PRD/on/demandware.static/-/Sites-ConverseMaster/default/dw3a00d7fc/images/a_107/A01203C_A_107X1.jpg?sw=2000"
  }
]

function get_data(){
    return data
}